apiVersion: apps/v1
kind: Deployment
namespace: argo_test_namespace
metadata:
  name: argo-test
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: argo-test
  template:
    metadata:
      labels:
        app: argo-test
    spec:
      containers:
      - image: kubeevo.azurecr.io/kubenohttps:latest
        name: argo-test
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: kubeevo-secret
