apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-test
  namespace: argocd
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: argo-test
  template:
    metadata:
      labels:
        app: argo-test
    spec:
      containers:
      - image: evok8sregistry.azurecr.io/evo-k8s-app:v2
        name: argo-test
        ports:
        - containerPort: 4200
      imagePullSecrets:
      - name: k8spullsecret
